### PR TITLE
Update example/website_loader for Cursive 0.3.0

### PR DESCRIPTION
**Pull request by gyscos**
Hi!

Cursive recently received a small update that broke backward compatibility ; here is a patch that makes it work again. It should make some of the most painful parts a bit cleaner.

I apologise for the inconvenience!

### CODE REVIEW

**Comment by Ogeon** [comment]
Hi, sorry for my delayed response. I didn't get a notification... I just wanted to make you aware of the reason, and will take an actual look at this a bit later.

**Comment by Ogeon** [comment]
I have finally had the time to take a look at this, and I bumped into this problem while trying to run the example:

```
error[E0308]: mismatched types
  --> /home/ogeon/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.3.1/src/backend/curses.rs:15:34
   |
15 |         ncurses::keypad(unsafe { ncurses::stdscr }, true);
   |                                  ^^^^^^^^^^^^^^^ expected *-ptr, found fn item
   |
   = note: expected type `*mut i8`
   = note:    found type `fn() -> *mut i8 {ncurses::stdscr}`
```

**Comment by Ogeon** [comment]
Also, I should probably add Travis tests...

**Comment by Ogeon** [comment]
Hmm... this seems to be a problem in cursive 0.2.6, as well.

**Comment by gyscos** [comment]
Indeed, ncurses was recently updated, breaking compatibility. It's fixed in the cursive master, I'll publish a version soon.

**Comment by Ogeon** [comment]
Alright, cool! I'll get those Travis tests going, to make life a bit easier on this end.

**Comment by Ogeon** [comment]
There we go. Rebasing this PR on top of `master` should enable the tests for it.

**Comment by gyscos** [comment]
The tests appear to be hanging?

**Comment by Ogeon** [comment]
Yeah, I have no idea what's going on. It seems like they are stuck in the queue, somehow. I have to sleep, anyway, so let's wait and see if they have unstuck them selves tomorrow.

**Comment by Ogeon** [comment]
Seems like they have noticed the problem and are trying to fix it. I restarted the build, just in case.

**Comment by Ogeon** [comment]
There are still problems with the OS X builds, but it seems like it's fine, anyway. I tried it, as well, and it runs great (except for the usual empty list crash). I'll just merge it. Thanks for your patience, and for doing this!

**Comment by gyscos** [comment]
Empty list crash? I'd be happy to look into it. What's the issue exactly?

**Comment by Ogeon** [comment]
It's really an effect of how I'm abusing it to be able to remove items, but still something that's good to fix. I was eventually going to report it, but forgot...

Anyway, try to run the example, add a URL, then remove it. The application crashes (for me, at least, on Ubuntu).

**Comment by gyscos** [comment]
Indeed, it should be fixed on cursive master. Thanks!

**Comment by Ogeon** [comment]
Nice!

**Pull request merged**
